M48
; DRILL file {KiCad 8.0.5} date 2025-01-19T00:45:51+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-19T00:45:51+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X143.922Y-79.567
X149.702Y-79.567
T2
X93.0Y-77.0
X93.0Y-141.0
X222.0Y-77.0
X222.0Y-141.0
M30
